### ISSUE TITLE
did not find the content

### ISSUE THREAD

**Issue by dcalixto** [cowboysmall-tools/hugo-business-frontpage-theme#1]
ok, after setup the theme, i created a simple about page on content/pages and show 404 page not found
 [[params.navbar.nav]]
        name = "About"
        url = "/pages/about"

**Comment by cowboysmall** [comment]
Hi,

It's a single page theme - the links I added in the example site were for consistency with the original template. So, unlike a typical blog theme, it does not support pages created in content. 

You could extend the theme within your project by adding an about.html page within 'layouts/_default' - maybe start out by copying index.html and making whatever changes you require.

Thanks,

J.K.
