### ISSUE TITLE
Insecure mixed content detected in theme demo

### ISSUE THREAD

**Issue by onedrawingperday** [cowboysmall-tools/hugo-business-frontpage-theme#2]
Hello I am one of the maintainers of Hugo Themes.

in the latest deploy Netlify has detected the following insecure asset in your theme's templates:

```
2:14:44 AM: Mixed content detected in: /theme/hugo-business-frontpage-theme/index.html
2:14:45 AM: --> insecure img urls:
2:14:45 AM:   - http://placehold.it/300x200
```
Please make sure to always use HTTPS for linked assets. 

Once you fix the above feel free to close this issue.

**Comment by cowboysmall** [comment]
Oops! An oversight. Resolved here - c5212be68d0726281a54a5842776a8af3ea38360

J.K.
